### ISSUE TITLE
Rediseño en DataBase.java

### ISSUE THREAD

**Issue by BryanEstrada003** [cbozan/employer-worker-registration-system#2]
Buenas noches, se sugiere rediseñar, implementando el patrón de diseño Singleton, esta clase dividiéndola en 2 clases, una que se encargue de tener la instancia de la base de datos, y otra que tenga todos los métodos para la manipulación de este. Por una parte, gracias a este rediseño, separamos las responsabilidades que antes tenía DataBase.java, además tenemos un acceso controlado a una instancia única de la base de datos.
![Singleton](https://user-images.githubusercontent.com/98861990/209421763-3bb32333-d748-4c18-9b07-7c503fcc913f.png)

**Comment by cbozan** [comment]
Thanks for the suggestion, you are absolutely right. I'm thinking of moving to MVC structure with design principles as soon as possible.
